blank_issues_enabled: true
contact_links:
  - name: Feature Request 💡
    url: https://github.com/l2hyunwoo/react-native-nitro-cookies/issues/new?title=Feature%20request%3A%20
    about: Describe the problem and the feature you propose in an issue.
  - name: Questions 💬
    url: https://github.com/l2hyunwoo/react-native-nitro-cookies/issues/new?title=Question%3A%20
    about: Ask a question in Issues and include the relevant versions and platform.
